server:
  http2:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:example}
    hikari:
      pool-name: AirTicketSystemHikariPool
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  jta:
    enabled: false

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework: INFO
    com.ziwok.airticketsystem.api: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: ziwok
  expirationMinute: 60

swagger:
  contact-name: Quoc Bui
  contact-mail: bvquoc.dev@gmail.com
  contact-url: https://www.facebook.com/bviquoc/
  app-name: Air Ticket System - Backend
  app-description: "Air Ticket Booking System using Java Spring Boot"
  app-version: 0.0.1
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
