create table if not exists users
(
    id        bigint generated by default as identity
    primary key,
    email     varchar(255),
    name      varchar(255),
    password  varchar(255),
    user_role varchar(255)
    constraint users_user_role_check
    check ((user_role)::text = ANY
(ARRAY [('USER'::character varying)::text, ('ADMIN'::character varying)::text])),
    username  varchar(255)
    unique
    );

alter table users
    owner to postgres;

create index if not exists idx_users_email
    on users (email);

create index if not exists idx_users_username
    on users (username);

create table if not exists bookings
(
    booking_id   serial
    primary key,
    user_id      bigint
    references users
    on delete cascade,
    booking_date timestamp default CURRENT_TIMESTAMP,
    total_amount numeric(10, 2),
    status       varchar(50)
    );

alter table bookings
    owner to postgres;

create table if not exists payments
(
    payment_id     serial
    primary key,
    booking_id     integer
    references bookings
    on delete cascade,
    payment_date   timestamp default CURRENT_TIMESTAMP,
    amount         numeric(10, 2),
    payment_method varchar(50),
    status         varchar(50)
    );

alter table payments
    owner to postgres;

create index if not exists idx_booking_id
    on payments (booking_id);

create table if not exists direction_bookings
(
    direction_booking_id serial
    primary key,
    booking_id           integer
    references bookings
    on delete cascade,
    origin               varchar(100),
    destination          varchar(100),
    departure_date       timestamp,
    arrival_date         timestamp
    );

alter table direction_bookings
    owner to postgres;

create table if not exists passengers
(
    passenger_id    serial
    primary key,
    first_name      varchar(100),
    last_name       varchar(100),
    date_of_birth   date,
    passport_number varchar(50),
    nationality     varchar(50)
    );

alter table passengers
    owner to postgres;

create table if not exists aircrafts
(
    aircraft_id      serial
    primary key,
    aircraft_model   varchar(100),
    manufacturer     varchar(100),
    seating_capacity integer
    );

alter table aircrafts
    owner to postgres;

create table if not exists flights
(
    flight_id      serial
    primary key,
    flight_number  varchar(50)
    unique,
    departure_time timestamp,
    arrival_time   timestamp,
    origin         varchar(100),
    destination    varchar(100),
    aircraft_id    integer
    references aircrafts
    on delete cascade
    );

alter table flights
    owner to postgres;

create table if not exists seats
(
    seat_id      serial
    primary key,
    aircraft_id  integer
    references aircrafts
    on delete cascade,
    seat_number  varchar(10),
    seat_type    varchar(50),
    is_available boolean default true
    );

alter table seats
    owner to postgres;

create table if not exists tickets
(
    ticket_id            serial
    primary key,
    direction_booking_id integer
    references direction_bookings
    on delete cascade,
    flight_id            integer
    references flights
    on delete cascade,
    seat_id              integer
    references seats
    on delete cascade,
    passenger_id         integer
    references passengers
    on delete cascade,
    ticket_status        varchar(50)
    );

alter table tickets
    owner to postgres;

create index if not exists idx_flight_id
    on tickets (flight_id);

create index if not exists idx_seat_id
    on tickets (seat_id);

create index if not exists idx_passenger_id
    on tickets (passenger_id);

